title: GSoC 22 Progress
email: dahalegopal27@gmail.com
description: Slides showing progress done during GSoC 22 with ML4SCI
baseurl:  ""
url: ""
github_username: Gopal-Dahale

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-spaceship