title: GSoC 22 Progress
email: dahalegopal@gmail.com
author: Gopal-Dahale
baseurl: "/gsoc-22-progress"
url: "https://gopal-dahale.github.io"
repository: Gopal-Dahale/gsoc-22-progress
theme: jekyll-theme-cayman
plugins:
  - jekyll-spaceship